### ISSUE TITLE
Задание 1: Создать файл Task1.md. Дальнейшие действия в описании

### ISSUE THREAD

**Issue by Alex-Yakubov** [Alex-Yakubov/Unit-test#1]
Представьте, что вы работаете над разработкой простого приложения для записной книжки, которое позволяет пользователям добавлять, редактировать и удалять контакты.
Ваша задача - придумать как можно больше различных тестов (юнит-тесты, интеграционные тесты, сквозные тесты) для этого приложения. Напишите название каждого теста, его тип и краткое описание того, что этот тест проверяет.

**Comment by Elena-Kulikova** [comment]
задание выполнено
